mealshop/app/urls.py
import uuid
from django.urls import path
from . import views

app_name = 'mealshop'

urlpatterns = [
    path('', views.index, name='index'),
    # Employees menu request
    path('menu/<uuid:uuid>', views.menu, name='menu'),
    path('<int:menu_id>/choose_menu/', views.choose_menu, name='choose_menu'),
    path('<int:menu_id>/add_order', views.add_order, name='add_order'),
    path('view_orders/', views.view_orders, name='view_orders'),
    path('<int:order_id>/add_order_customizations',
         views.add_order_customizations, name='add_order_customizations'),
    # Menu paths
    path('create_menu/',
         views.create_menu, name='create_menu'),
    path('add_menu/',
         views.add_menu, name='add_menu'),
    path('<int:menu_id>/update_daily_menu',
         views.update_daily_menu, name='update_daily_menu'),
    path('daily_menu/', views.daily_menu, name='daily_menu'),
    path('<int:menu_id>/create_reminder', views.create_reminder,
         name='create_reminder'),
    # Menu Option paths
    path('<int:menu_option_id>/menu_option/',
         views.menu_option, name='menu_option'),
    path('<int:menu_option_id>/add_customization/',
         views.add_customization, name='add_customization'),
    path('menu_options/',
         views.menu_options, name='menu_options'),
    path('add_menu_option/',
         views.add_menu_option, name='add_menu_option')
]

mealshop/mealshop/urls.py
from django.urls import path
from django.urls import include, path
from register import views as v


urlpatterns = [
    path('', include('app.urls')),
    path('register/', v.register,  name='register'),
    path('', include('django.contrib.auth.urls'))
]

mealshop/app/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class MenuOption(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()

    def __str__(self):
        return self.name


class MenuOptionCustomization(models.Model):
    name = models.CharField(max_length=250)
    menu_option = models.ForeignKey(MenuOption, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Menu(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='menu', null=True)
    menu_options = models.ManyToManyField(MenuOption)
    pub_date = models.DateTimeField('date published', default=now)
    slack_url = models.CharField(max_length=300)

    def __str__(self):
        return str(self.pub_date)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='order', null=True)
    menu_option = models.ForeignKey(
        MenuOption, on_delete=models.CASCADE, default=None)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, null=False)
    purchased_date = models.DateTimeField(
        'purchased date', default=now)

    def __str__(self):
        return 'user {} option {} on date {}'.format(
            self.user, self.menu_option, self.purchased_date)


class OrderCustomization(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    menu_option_custom = models.ForeignKey(
        MenuOptionCustomization, on_delete=models.CASCADE)

    def __str__(self):
        return 'order {} \nmenu_option_custom {}'.format(
            self.order, self.menu_option_custom)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slack_user = models.CharField(max_length=100, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

mealshop/app/templates/app/base.html
<!doctype html>
<html lang="es">
<head>
    <style>
        .sidenav {
            height: 100%;
            width: 160px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #2c2c2e;
        }
        .sidenav div {
            padding: 6px 8px 6px 12px;
            text-decoration: none;
            color: #ff0026;
            display: block;
        }
        .sidenav a {
            padding: 6px 8px 6px 12px;
            text-decoration: none;
            color: #FFF;
            display: block;
        }
        .sidenav a:hover{
            color: #ff0026;
        }
        .sidenav hr {
            border: 1px solid red;
            padding: 1px 1px;
        }
        .main {
            margin-left: 160px;
            padding: 0 10px;
        }
    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% block title %}MealShop{% endblock %}</title>
</head>

<body>
    <div class="sidenav">
        <div>{{ user }}</div>
        <a href="/">Ver listas de menus </a>
        <a href="/login">Iniciar sesión</a>
        <a href="/register">Registarse</a>
        {% if perms.app.add_menu %}
        <hr >
        <div>Proveedor</div>
        <a href="/daily_menu">Ver menu del día</a>
        <a href="/view_orders">Ordenes del día</a>
        <a href="/create_menu/">Crear menú</a>
        <a href="/menu_options">Opciones de menú</a>
        {% endif %}
    </div>
    <div id="content" name="content" class="main">
        <div class="row justify-content-center">
            <div class="col-8">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div> 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
</body>
</html>

mealshop/app/templates/app/choose_menu.html
{% extends 'app/base.html' %}
{% block title %}
    Elegir menú
{% endblock %}

{% block content %}

<h2 class="mt-2">Menú del día, se cerrará a las 11:00am</h2>
<hr class="mt-0 mb-4">

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if menu %}
<form action="{% url 'mealshop:add_order' menu.id %}" method="post" class="form-group">
    {% csrf_token %}
        {% for option in menu.menu_options.all %}
        <div class="form-check">
            <input class="form-check-input" type="radio" name="menu_option_id" id="{{option.id}}" value="{{option.id}}" />
            <label class="form-check-label" for="{{option.id}}">{{ option.name }}</label>
        </div>
        {% endfor %}
        {% if order %}
        <div class="input-group">
            <input type="hidden" value="{{ order.id }}" />
            <button type="submit" value="Actualizar" class="btn btn-success">Actualizar</button>
        </div>
        {% else %}
        <div class="input-group">
            <button type="submit" value="Elegir" class="btn btn-success">Elegir</button>
        </div>
        {% endif %}
</form>
{% if order %}
    <h3>Orden pedida:</h3>
    <p>{{ order.menu_option.name }}</p>
    
    <h3>Customizaciones</h3>
    <form action="{% url 'mealshop:add_order_customizations' order.id %}" method="post" class="form-group">
        {% csrf_token %}
            {% for customization in order.menu_option.menuoptioncustomization_set.all %}
            <div class="form-check">
                {% if customization.id in customization_user  %}
                    <input type="checkbox" 
                        id="{{customization.id}}"
                        name="menu_option_customization_{{customization.id}}" checked  class="form-check-input" />
                {% else %}
                    <input type="checkbox" 
                        id="{{customization.id}}"
                        name="menu_option_customization_{{customization.id}}" class="form-check-input" />
                {% endif %}
                    <label for="{{customization.id}}" class="form-check-label">{{ customization.name }}</label>
            </div>
            {% endfor %}
    <div class="input-group">
        <button type="submit" value="Customizar" class="btn btn-success">Customizar</button>
    </div>
    </form>
{% else %}
    <p>Elige tu orden, además agrega tus customizaciones si existen</p>
{% endif %}

{% else %}
<p>
    Se ha cerrado el menu del día, esperar a que mañana se habilite, tenga lindo día :)
</p>
{% endif %}

{% endblock %}

mealshop/app/templates/app/create_menu.html
{% extends 'app/base.html' %}
{% block title %}
    Elegir menú
{% endblock %}

{% block content %}

<h2 class="mt-2">Crear menú para el día </h2>
<hr class="mt-0 mb-4">

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'mealshop:add_menu' %}" method="post">
    {% csrf_token %}
    <h3>Elegir opciones de menu </h3>
    <ul>
    {% for option in menu_options %}
        <li> 
            <label for="menu_option_{{option.id}}">{{ option.name }}</label>
            <input type="checkbox" name="menu_option_{{option.id}}" id="{{option.id}}" />
        </li>
    {% endfor %}
    </ul>
    <div>
        <label for="date">Elegir fecha</label>
        <input type="text" name="pub_date" id="datetimepicker" />
    </div>

    <input type="submit" value="Crear">
</form>
<script type="text/javascript">
    window.onload = function() { 
        $("#datetimepicker").datepicker().datepicker("setDate", new Date());
    }
</script>

{% endblock %}

mealshop/app/templates/app/daily_menu.html
{% extends 'app/base.html' %}
{% block title %}
    Elegir menú
{% endblock %}

{% block content %}

<h2 class="mt-2">Menú del día</h2>
<hr class="mt-0 mb-4">

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if menu %}
    <p>
        {{ menu.pub_date }}
    </p>
    <ul>
    {% for option in menu.menu_options.all %}
        <li> {{ option.name }} </li>
    {% endfor %}
    </ul>

    <p>
        <a href="{% url 'mealshop:create_reminder' menu.id %}">
            Mandar recordatorio de menú a los empleados
        </a>
    </p>
    <p>
        <a href="{% url 'mealshop:update_daily_menu' menu.id %}">
            Actualizar menú del día
        </a>
    </P>
{% else %}
    <a href="{% url 'mealshop:create_menu' %}">
        Crear menú del día
    </a>
{% endif %}

{% endblock %}

mealshop/app/templates/app/index.html
{% extends 'app/base.html' %}
{% block title %}
    Home
{% endblock %}

{% block content %}
<h2 class="mt-2">Bienvernido a MealShop</h2>
<hr class="mt-0 mb-4">

<p>Hola, applicación para hacer pedido de menus de la doña Nora</p>
{% if menu %}
<p>
    Puedes ver el menu de nora en este link: 
    <a href="{% url 'mealshop:menu' menu.uuid %}">Menu del día</a>
</p>
{% else %}
<p>
    No hay menú para elegir :(
</p>
{% endif %}

{% endblock %}

mealshop/app/templates/app/list_menu_options.html
{% extends 'app/base.html' %}
{% block title %}
    Elegir menú
{% endblock %}

{% block content %}

<h2 class="mt-2"> Lista de opciones menu</h2>
<hr class="mt-0 mb-4">

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'mealshop:add_menu_option' %}" method="post">
    {% csrf_token %}
    <label for="menu_option_customization">Agregar opción de menú</label><br>
    <input type="text" name="menu_option_name" id="menu_option_name" value="" />
    <input type="submit" value="menu_option">
</form>

<ul>
{% for option in menu_options %}
    <li> 
        <a href="{% url 'mealshop:menu_option' option.id %}">
            {{ option.name }}
        </a>  
    </li>
{% endfor %}
</ul>

{% endblock %}

mealshop/app/templates/app/menu.html
{% extends 'app/base.html' %}
{% block title %}
    Menu del día
{% endblock %}

{% block content %}

<h2 class="mt-2">Menú del día, se cerrará a las 11:00am</h2>
<hr class="mt-0 mb-4">

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if menu %}
    <ul class="list-group">
    {% for option in menu.menu_options.all %}
        <li class="">Opcion  {{ forloop.counter }}: {{ option.name }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'mealshop:choose_menu' menu.id %}">Elegír acá</a>
{% else %}
<p>
    Se ha cerrado el menu del día, esperar a que mañana se habilite, tenga lindo día :)
</p>
{% endif %}

{% endblock %}

mealshop/app/templates/app/menu_option.html
{% extends 'app/base.html' %}
{% block title %}
    Elegir menú
{% endblock %}

{% block content %}

<h2 class="mt-2">{{ menu_option.name }}</h2>
<hr class="mt-0 mb-4">

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'mealshop:add_customization' menu_option.id %}" method="post">
    {% csrf_token %}
    <label for="menu_option_customization">Agregar customización al plato</label><br>
    <input type="text" name="menu_option_customization" id="menu_option_customization" value="" />
    <input type="submit" value="customization">
</form>

<h1> Lista de customizaciones para un plato</h1>
<ul>
{% for option in menu_option.menuoptioncustomization_set.all  %}
    <li> {{ option.name }}  </li>
{% endfor %}
</ul>

{% endblock %}

mealshop/app/templates/app/menu_update.html
{% extends 'app/base.html' %}
{% block title %}
    Menú del día
{% endblock %}

{% block content %}
<h1>Actualizar menú del día</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'mealshop:update_daily_menu' menu.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="menu_option">
</form>
{% endblock %}

mealshop/app/templates/app/view_orders.html
{% extends 'app/base.html' %}
{% block title %}
    Ordenes del día
{% endblock %}

{% block content %}
<h2 class="mt-2"> Ordernes del día </h2>
<hr class="mt-0 mb-4">

{% for order in orders %}
    <uL>
        <li> 
            <p>
            El usuario <strong>{{ order.user.username }}</strong> ordeno: {{ order.menu_option.name }}
            </p>
            <p>
            <ul>
            {% for customization in order.ordercustomization_set.all %}
                <li>
                    {{ customization.menu_option_custom.name }}
                </li>
            {% endfor %}
            </ul>
            </p>
        </li>
    </ul>
{% endfor %}

{% endblock %}